#game parameters
FPS = 100
GAME_TITLE = "Space Wars"
# screen parameters
SCREEN_WIDTH = 700
SCREEN_HEIGHT = 700
SCREEN_X = 0
SCREEN_Y = 0
SCREEN_BACKGROUND_IMAGE_PATH = "res/images/background.jpg"
SCREEN_MOVE_SPEED = 4

# main player parameters
PLAYER_WIDTH = 60
PLAYER_HEIGHT = 60
PLAYER_START_X = SCREEN_WIDTH / 2 - PLAYER_WIDTH / 2
PLAYER_START_Y = SCREEN_HEIGHT - PLAYER_HEIGHT - 50
PLAYER_INITIAL_IMAGE_PATH = "res/images/player.png"
PLAYER_MOVE_SPEED = 5

# enemy parameters
ENEMY_HEIGHT = 60
ENEMY_WIDTH = 60
ENEMY_START_X = SCREEN_WIDTH / 2 - ENEMY_WIDTH / 2
ENEMY_START_Y = 0
ENEMY_MOVE_SPEED = 2

#bullet parameters

BULLET_WIDTH = 8
BULLET_HEIGHT = 16
BULLET_MOVE_SPEED = 2
BULLET_SPLIT_LENGTH = 90

MAIN_PLAYER_BULLET_IMAGE_PATH = "res/images/fire.png"
MAIN_PLAYER_BULLET_DAMAGE = 100

ENEMY_BULLET_IMAGE_PATH = "res/images/fire.png"#TODO
